service: serverless-pdf-simplificado

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-stage-manager
#  - serverless-plugin-optimize

custom:
  stages:
    - dev
    - test
    - acc
    - prod

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 20
  memorySize: 1536

functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: any
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:libreoffice-brotli:1

package:
    patterns:
      - '!.git*'
      - '!.vscode'
      - '!.gitignore'
      - '!README.md'
      - '!serverless.yml'
    excludeDevDependencies: true
    individually: true